name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # CI Job
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt                    
  
    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: app-package
        path: |
          lambda_function.zip
          # You can include any other artifacts needed in CD
      run: |
        zip -r lambda_function.zip .
