name: Deploy to AWS Lambda (CI/CD)

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger deployment on pull requests targeting the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Use the appropriate Python version for your FastAPI app

    - name: Install Python Virtual ENV
      run: pip3 install virtualenv
   
    - name: Cache Virtual ENV
      uses: actions/cache@v2
      id: cache-venv 
      with:
        path: venv 
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Build and Activate Virtual ENV, Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
      if: steps.cache-venv.outputs.cache-hit != 'true'

    - name: Package Lambda function
      run: |
        mkdir -p package
        shopt -s extglob
        cp -r !(package) ./package/
        cd package && zip -r ../function.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}  # Change to your AWS region

    - name: Upload to S3
      run: aws s3 cp function.zip s3://fastapiscd/function.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Deploy new Lambda
      run: aws lambda update-function-code --function-name fastapi --s3-bucket fastapiscd --s3-key function.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}